Add support for compilation on Arm Mac
These are fixes for some errors I ran into while trying to compile this
locally on an Arm Mac.

The change to the Makefile is because `uname -p` on an M1 Mac returns
`arm`, not `aarch64`. We still want this to set the `ARCH` variable to
`aarch64`.

The addition to the .cargo/config ensures that the same rustflags that
are being passed for x86_64 are also passed when compiling for the
aarch64 target. Without this there are linking errors in the `make
wasmcloud-nif` step that look like:

    error: linking with `cc` failed: exit status: 1
    .
    .
    .
    ld: symbol(s) not found for architecture arm64
    clang: error: linker command failed with exit code 1 (use -v to see invocation)